//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motor_Tracker_Configuration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ViStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Motor_Tracker_Configuration.Resources.ViStrings", typeof(ViStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMBO Parameter Setup.
        /// </summary>
        internal static string APP_CAPTION_STR {
            get {
                return ResourceManager.GetString("APP_CAPTION_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể mở cổng .
        /// </summary>
        internal static string CANNOT_OPEN_COMPORT_STR {
            get {
                return ResourceManager.GetString("CANNOT_OPEN_COMPORT_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể mở file .
        /// </summary>
        internal static string CANNOT_OPEN_FILE_STR {
            get {
                return ResourceManager.GetString("CANNOT_OPEN_FILE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cập nhật cấu hình!.
        /// </summary>
        internal static string CONFIG_LOADED_STR {
            get {
                return ResourceManager.GetString("CONFIG_LOADED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File cấu hình được lưu ở .
        /// </summary>
        internal static string CONFIG_SAVE_SUCCESS_STR {
            get {
                return ResourceManager.GetString("CONFIG_SAVE_SUCCESS_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Đã kết nối.
        /// </summary>
        internal static string CONNECTED_STR {
            get {
                return ResourceManager.GetString("CONNECTED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy chủ Dữ liệu.
        /// </summary>
        internal static string DATA_SERVER_CMBBOX_ITEM_STR {
            get {
                return ResourceManager.GetString("DATA_SERVER_CMBBOX_ITEM_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa kết nối.
        /// </summary>
        internal static string DISCONNECTED_STR {
            get {
                return ResourceManager.GetString("DISCONNECTED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang cập nhật firmware....
        /// </summary>
        internal static string DOWNLOADING_FIRMWARE_STR {
            get {
                return ResourceManager.GetString("DOWNLOADING_FIRMWARE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên file không hợp lệ!.
        /// </summary>
        internal static string FILE_NAME_IS_INVALID_WARNING_STR {
            get {
                return ResourceManager.GetString("FILE_NAME_IS_INVALID_WARNING_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật firmware thất bại!.
        /// </summary>
        internal static string FIRMWARE_DOWNLOADED_FAILED_STR {
            get {
                return ResourceManager.GetString("FIRMWARE_DOWNLOADED_FAILED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật firmware thành công!.
        /// </summary>
        internal static string FIRMWARE_DOWNLOADED_SUCCESS_STR {
            get {
                return ResourceManager.GetString("FIRMWARE_DOWNLOADED_SUCCESS_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy chủ Firmware.
        /// </summary>
        internal static string FIRMWARE_SERVER_CMBBOX_ITEM_STR {
            get {
                return ResourceManager.GetString("FIRMWARE_SERVER_CMBBOX_ITEM_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format thẻ nhớ sẽ mất vài phút để hoàn thành. Vui lòng không tắt nguồn trước khi kết thúc format!.
        /// </summary>
        internal static string FORMAT_SDCARD_WARNING_STR {
            get {
                return ResourceManager.GetString("FORMAT_SDCARD_WARNING_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy chủ Thông tin.
        /// </summary>
        internal static string INFO_SERVER_CMBBOX_ITEM_STR {
            get {
                return ResourceManager.GetString("INFO_SERVER_CMBBOX_ITEM_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chu kỳ.
        /// </summary>
        internal static string INTERVAL_TRIGGER_SOURCE_CHKLIST_ITEM_STR {
            get {
                return ResourceManager.GetString("INTERVAL_TRIGGER_SOURCE_CHKLIST_ITEM_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File KML được lưu ở .
        /// </summary>
        internal static string KML_SAVE_SUCCESS_STR {
            get {
                return ResourceManager.GetString("KML_SAVE_SUCCESS_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 phút.
        /// </summary>
        internal static string LOG_INTERVAL_1_MIN_STR {
            get {
                return ResourceManager.GetString("LOG_INTERVAL_1_MIN_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 phút.
        /// </summary>
        internal static string LOG_INTERVAL_10_MIN_STR {
            get {
                return ResourceManager.GetString("LOG_INTERVAL_10_MIN_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 phút.
        /// </summary>
        internal static string LOG_INTERVAL_30_MIN_STR {
            get {
                return ResourceManager.GetString("LOG_INTERVAL_30_MIN_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 phút.
        /// </summary>
        internal static string LOG_INTERVAL_5_MIN_STR {
            get {
                return ResourceManager.GetString("LOG_INTERVAL_5_MIN_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở File.
        /// </summary>
        internal static string OPEN_FILE_DIALOG_TITLE_STR {
            get {
                return ResourceManager.GetString("OPEN_FILE_DIALOG_TITLE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Log Folder.
        /// </summary>
        internal static string OPEN_FOLDER_DIALOG_TITLE_STR {
            get {
                return ResourceManager.GetString("OPEN_FOLDER_DIALOG_TITLE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đọc cấu hình thất bại!.
        /// </summary>
        internal static string READ_CONFIG_FAILED_STR {
            get {
                return ResourceManager.GetString("READ_CONFIG_FAILED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đọc cấu hình thành công!.
        /// </summary>
        internal static string READ_CONFIG_SUCCESS_STR {
            get {
                return ResourceManager.GetString("READ_CONFIG_SUCCESS_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang nhận file .
        /// </summary>
        internal static string RETRIEVING_FILE_STR {
            get {
                return ResourceManager.GetString("RETRIEVING_FILE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu File.
        /// </summary>
        internal static string SAVE_FILE_DIALOG_TITLE_STR {
            get {
                return ResourceManager.GetString("SAVE_FILE_DIALOG_TITLE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt camera Id thất bại!.
        /// </summary>
        internal static string SET_CAMERA_ID_FAILED {
            get {
                return ResourceManager.GetString("SET_CAMERA_ID_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt camera Id thành công!.
        /// </summary>
        internal static string SET_CAMERA_ID_SUCCESS {
            get {
                return ResourceManager.GetString("SET_CAMERA_ID_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu cấu hình thất bại!.
        /// </summary>
        internal static string WRITE_CONFIG_FALIED_STR {
            get {
                return ResourceManager.GetString("WRITE_CONFIG_FALIED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu cấu hình thành công!.
        /// </summary>
        internal static string WRITE_CONFIG_SUCCESS_STR {
            get {
                return ResourceManager.GetString("WRITE_CONFIG_SUCCESS_STR", resourceCulture);
            }
        }
    }
}
